[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.44.0", features = ["full"] }
env_logger = "0.11.7"
log = "0.4.26"
