version: '3.9'

services:
  wso2:
    image: wso2/wso2is:7.0.0
    container_name: wso2is
    network_mode: host
    volumes:
      # - ./wso2/carbon.xml:/home/wso2carbon/wso2is-7.0.0/repository/conf/carbon.xml
      - ./wso2/deployment.toml:/home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
    ports:
      - "9443:9443"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  # ldap:
  #   image: osixia/openldap:latest
  #   container_name: ldap
  #   environment:
  #     LDAP_ORGANISATION: "lambdabytes"
  #     LDAP_DOMAIN: "example.com"
  #     LDAP_ADMIN_PASSWORD: "admin"
  #   ports:
  #     - "389:389"
  #     - "636:636"
  #   volumes:
  #     - ldap_data:/var/lib/ldap
  #     - ldap_config:/etc/ldap/slapd.d

  # phpldapadmin:
  #   image: osixia/phpldapadmin
  #   container_name: phpldapadmin
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: "ldap"
  #     PHPLDAPADMIN_HTTPS: "false"
  #     PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
  #   ports:
  #     - "8081:80"

